services:
  ics_bridge:
    build: .
    container_name: ics-bridge
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
